# Generated by Django 3.1 on 2020-08-23 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlcut', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturl',
            name='visits_count',
        ),
    ]
